name: release

on:
  release:
    types: [published]

env:
  UV_VERSION: "0.4.x"

permissions:
  contents: write

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  pypi:
    runs-on: ubuntu-latest
    needs: test
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: ${{ env.UV_VERSION }}

      - name: Build package
        run: |
          uv build

      - name: Upload release assets to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in dist/*; do
            gh release upload ${{ github.event.release.tag_name }} "$file" --clobber
          done

      - name: Publish to PyPI
        run: |
          uv publish
